#!/usr/bin/env bash
# Script to generate koboldcpp-models.nix from models in /media/gai/koboldcpp/
# Run this whenever you add/remove models to regenerate the model maps

set -euo pipefail

KOBOLDCPP_DIR="/media/gai/koboldcpp"
OUTPUT_FILE="/home/aurelia/Projects/universe/systems/fool/koboldcpp-models.nix"

# Check if directories exist
if [[ ! -d "$KOBOLDCPP_DIR/main" ]]; then
    echo "Error: $KOBOLDCPP_DIR/main does not exist"
    exit 1
fi

# Function to extract model name from filename
extract_model_name() {
    local filename="$1"
    # Remove extension
    local name="${filename%.*}"
    # Remove TheDrummer_ prefix if present
    name="${name#TheDrummer_}"
    echo "$name"
}

# Function to convert model name to valid Nix attribute name
to_nix_attr() {
    local name="$1"
    # Replace - and . with _
    echo "$name" | sed 's/[-.]/_/g' | sed 's/^[0-9]/_&/'
}

# Function to generate attribute set for a directory
generate_file_map() {
    local dir="$1"
    local pattern="$2"

    shopt -s nullglob
    for file in "$KOBOLDCPP_DIR/$dir"/$pattern; do
        [[ -f "$file" ]] || continue

        filename=$(basename "$file")
        model_name=$(extract_model_name "$filename")
        attr_name=$(to_nix_attr "$model_name")

        echo "    \"$attr_name\" = \"$filename\";"
    done
    shopt -u nullglob
}

# Start generating the Nix file
cat > "$OUTPUT_FILE" << 'EOF'
# Auto-generated by contrib/generate-koboldcpp-configs.sh
# DO NOT EDIT MANUALLY - Run the script to regenerate
# Maps of model names to filenames found in /media/gai/koboldcpp/

{
  main = {
EOF

# Generate main models map
generate_file_map "main" "*.gguf" >> "$OUTPUT_FILE"

cat >> "$OUTPUT_FILE" << 'EOF'
  };

  embeddings = {
EOF

# Generate embeddings map
generate_file_map "embeddings" "*.gguf" >> "$OUTPUT_FILE"

cat >> "$OUTPUT_FILE" << 'EOF'
  };

  tts = {
EOF

# Generate TTS map
generate_file_map "tts" "*.gguf" >> "$OUTPUT_FILE"

cat >> "$OUTPUT_FILE" << 'EOF'
  };

  whisper = {
EOF

# Generate whisper map
generate_file_map "whisper" "*.bin" >> "$OUTPUT_FILE"

cat >> "$OUTPUT_FILE" << 'EOF'
  };

  image = {
EOF

# Generate image models map (both .gguf and .safetensors)
generate_file_map "image" "*.gguf" >> "$OUTPUT_FILE"
generate_file_map "image" "*.safetensors" >> "$OUTPUT_FILE"

cat >> "$OUTPUT_FILE" << 'EOF'
  };

  clip = {
EOF

# Generate CLIP map
generate_file_map "clip" "*.gguf" >> "$OUTPUT_FILE"

cat >> "$OUTPUT_FILE" << 'EOF'
  };

  mmproj = {
EOF

# Generate multimodal projection map
generate_file_map "mmproj" "*.gguf" >> "$OUTPUT_FILE"

cat >> "$OUTPUT_FILE" << 'EOF'
  };
}
EOF

# Count models
main_count=$(ls -1 "$KOBOLDCPP_DIR/main"/*.gguf 2>/dev/null | wc -l)
embeddings_count=$(ls -1 "$KOBOLDCPP_DIR/embeddings"/*.gguf 2>/dev/null | wc -l)
tts_count=$(ls -1 "$KOBOLDCPP_DIR/tts"/*.gguf 2>/dev/null | wc -l)
whisper_count=$(ls -1 "$KOBOLDCPP_DIR/whisper"/*.bin 2>/dev/null | wc -l)
image_count=$(ls -1 "$KOBOLDCPP_DIR/image"/*.{gguf,safetensors} 2>/dev/null | wc -l)
clip_count=$(ls -1 "$KOBOLDCPP_DIR/clip"/*.gguf 2>/dev/null | wc -l)
mmproj_count=$(ls -1 "$KOBOLDCPP_DIR/mmproj"/*.gguf 2>/dev/null | wc -l)

echo "Generated $OUTPUT_FILE"
echo ""
echo "Summary:"
echo "  Main models:       $main_count"
echo "  Embeddings:        $embeddings_count"
echo "  TTS:               $tts_count"
echo "  Whisper:           $whisper_count"
echo "  Image models:      $image_count"
echo "  CLIP:              $clip_count"
echo "  Multimodal proj:   $mmproj_count"
