# Auto-generated by contrib/generate-koboldcpp-configs.sh
# DO NOT EDIT MANUALLY - Run the script to regenerate
# Maps of model names to filenames found in /media/gai/koboldcpp/

{
  main = {
    "Buddy_2B_v1_Q6k" = "Buddy-2B-v1_Q6k.gguf";
    "Cydonia_24B_v4zk_Q4_K_M" = "Cydonia-24B-v4zk-Q4_K_M.gguf";
    "gemma_3_27b_it_abliterated_q3_k_m" = "gemma-3-27b-it-abliterated.q3_k_m.gguf";
    "gpt_oss_20b_Derestricted_Q4_K_S" = "gpt-oss-20b-Derestricted.Q4_K_S.gguf";
    "Skyfall_31B_v4r_Q4_K_M" = "Skyfall-31B-v4r-Q4_K_M.gguf";
    "Skyfall_31B_v4r_Q8_0" = "Skyfall-31B-v4r-Q8_0.gguf";
    "Skyfall_31B_v4w_Q4_K_M" = "Skyfall-31B-v4w-Q4_K_M.gguf";
    "Snowpiercer_15B_v3c_Q6_K" = "Snowpiercer-15B-v3c-Q6_K.gguf";
    "Snowpiercer_15B_v3c_Q8_0" = "Snowpiercer-15B-v3c-Q8_0.gguf";
    "Magidonia_24B_v4_3_Q4_K_M" = "TheDrummer_Magidonia-24B-v4.3-Q4_K_M.gguf";
    "Magidonia_24B_v4_3_Q6_K_L" = "TheDrummer_Magidonia-24B-v4.3-Q6_K_L.gguf";
    "Snowpiercer_15B_v4_Q6_K_L" = "TheDrummer_Snowpiercer-15B-v4-Q6_K_L.gguf";
    "Valkyrie_49B_v1_IQ3_M" = "TheDrummer_Valkyrie-49B-v1-IQ3_M.gguf";
    "Valkyrie_49B_v1_IQ4_XS" = "TheDrummer_Valkyrie-49B-v1-IQ4_XS.gguf";
    "Valkyrie_49B_v1_Q3_K_XL" = "TheDrummer_Valkyrie-49B-v1-Q3_K_XL.gguf";
  };

  embeddings = {
    "bge_m3_q8_0" = "bge-m3-q8_0.gguf";
  };

  tts = {
    "Kokoro_no_espeak_Q4" = "Kokoro_no_espeak_Q4.gguf";
  };

  whisper = {
    "whisper_base_en_q5_1" = "whisper-base.en-q5_1.bin";
  };

  image = {
    "z_image_turbo_Q4_0" = "z_image_turbo-Q4_0.gguf";
    "ae" = "ae.safetensors";
    "illustrij_v19" = "illustrij_v19.safetensors";
    "noobaiXLNAIXL_vPred10Version" = "noobaiXLNAIXL_vPred10Version.safetensors";
  };

  clip = {
    "Qwen3_4B_Instruct_2507_Q4_K_S" = "Qwen3-4B-Instruct-2507-Q4_K_S.gguf";
  };

  mmproj = {
    "Ministral_3_3B_Instruct_2512_mmproj_Q8_0" = "Ministral-3-3B-Instruct-2512-mmproj-Q8_0.gguf";
  };
}
