name: Update Nix Flake Dependencies and Build NixOS System

on:
  workflow_dispatch:

permissions:
  pull-requests: write
  contents: write

jobs:
  update-and-build:
    runs-on: blacksmith-8vcpu-ubuntu-2404

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: install lix
        uses: canidae-solutions/lix-quick-install-action@v3
      - name: Create new branch
        id: branch
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            BRANCH_NAME="update-flake-deps-$(openssl rand -hex 3)"
          else
            BRANCH_NAME="update-flake-deps-$(date +'%Y%m%d')"
          fi
          echo "branch=$BRANCH_NAME" >> $GITHUB_OUTPUT
      - name: Update flake dependencies
        id: update
        run: |
          nix flake update
          if git diff --quiet; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi
      - name: Setup attic
        run: |
          nix profile install nixpkgs/fa64ec5c1ca6f17746f3defedb988b9248e97616#attic-client
          attic login server ${{ vars.ATTIC_ENDPOINT }} ${{ secrets.ATTIC_TOKEN }}
          attic use ${{ vars.ATTIC_CACHE }}
      - name: Build NixOS system
        if: steps.update.outputs.changed == 'true'
        run: |
          nix build .#nixosConfigurations.fool.config.system.build.toplevel
      - name: Push cache
        run: |
          attic push ${{ vars.ATTIC_CACHE }} result
          rm result
      - name: Push changes
        if: steps.update.outputs.changed == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ steps.branch.outputs.branch }}
          force: true
      - name: Create Pull Request
        if: steps.update.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ steps.branch.outputs.branch }}
          title: "Update Nix Flake Dependencies"
          body: "This PR updates the Nix flake dependencies."
          reviewers: "acuteaura"
